### ISSUE TITLE
Boost trap missing or the path is wrongs?

### ISSUE THREAD

**Issue by thanhrohan1** [datlechin/DichVu-MXH#44]
I have a Issue here @@
after set up all the composer, Mysql ... then run >_  npm run production have error in 99% 

> [webpack-cli] [Error: ENOENT: no such file or directory, open 'C:\DichVu-MXH-master\public\assets\css\bootstrap.css'] {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>  path: 'C:\\DichVu-MXH-master\\public\\assets\\css\\bootstrap.css'
> }

How to fix this , Many thanks :3

**Comment by datlechin** [comment]
Hi, mới vừa mới push hotfix lên, bạn thử lại.

Nào có thời gian mình update lại source
